Received: from localhost; Fri May 16 14:31:17 CEST 2008
Message-ID: <482D77CD.9040709@xsocket.org>
Date: Fri, 16 May 2008 14:02:21 +0200
From: tester <tester@xsocket.org>
User-Agent: Thunderbird 2.0.0.9 (Windows/20071031)
MIME-Version: 1.0
To: test@xsocket.org
Subject: simple mail
Content-Type: text/plain; charset=ISO-8859-15; format=flowed
Content-Transfer-Encoding: 7bit

Hi,

this is a simple text mail

regards
tester